services:
  app:
    container_name: sensors-reader
    image: weatherstationproject/sensors
    privileged: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MINUTES_BETWEEN_READINGS=5
      - ENVIRONMENT=production
      - READ_ONLY=false
      - LOG_LEVEL=debug
      - USER=sensors
      - PASSWORD=<changeme>
      - ROOT_URL=https://192.168.1.1:8080
      - SOCKET_URL=https://192.168.1.1:8081
      - BME280_SENSOR_ENABLED=true
      - GROUND_TEMPERATURE_SENSOR_ENABLED=true
      - RAIN_GAUGE_ENABLED=true
      - ANEMOMETER_ENABLED=true
      - TZ=Europe/Madrid
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318
      - OTEL_DEBUG_IN_CONSOLE=False
      - OTEL_SERVICE_VERSION=1.0.0
      - OTEL_DEPLOYMENT_ENVIRONMENT=production
