services:
  app:
    container_name: sensors-reader
    image: weatherstationproject/sensors
    privileged: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=production
      - READ_ONLY=false
      - LOG_LEVEL=debug
      - USER=sensors
      - PASSWORD=<changeme>
      - ROOT_URL=http://192.168.1.1:8080
      - BME280_SENSOR_ENABLED=true
      - GROUND_TEMPERATURE_SENSOR_ENABLED=true
      - RAIN_GAUGE_ENABLED=true
      - ANEMOMETER_ENABLED=true
      - TZ=Europe/Madrid
